name: Deploy Auth Service to Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - 'services/auth-service/**'
      - '.github/workflows/deploy.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/neetchamp-auth-service:latest -f services/auth-service/Dockerfile .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/neetchamp-auth-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Create Kubernetes Secret for GHCR
        run: |
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ secrets.GHCR_USERNAME }} \
            --docker-password=${{ secrets.GHCR_TOKEN }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment/k8s/auth-service-deployment.yaml

      - name: Restart Deployment
        run: kubectl rollout restart deployment auth-service
